### PR TITLE
Enhance gtags environment

### PR DESCRIPTION
**Pull request by dean-ho**
Auto update & clear gtags environment variable $GTAGSROOT & $GTAGSDBPATH when the path in denite context is not same as CWD.

### CODE REVIEW

**Comment by ozelentok** [comment]
What are the use cases that require this changes?
Mind that `os.getcwd()` returns the python working directory and not the current vim file working directory, so `GTAGSROOT` might hold a wrong path
I also see that `GTAGSROOT` and `GTAGSDBPATH` are either overwritten by `os.getcwd()` and `context['path']` or are ignored, meaning that `GTAGSROOT` and `GTAGSDBPATH` cannot be set to other paths

**Comment by dean-ho** [comment]
I use ```ludovicchabant/vim-gutentags``` to manage tag database.
The tag files will be generated to a specified path, so I set up vimrc to auto detect tag files' path and map key with denite-gtags
```
function! s:get_gtags_file_path() abort
  if !exists('b:gutentags_files')
    return expand('%:p:h')
  endif
  if !has_key(b:gutentags_files, 'gtags_cscope')
    return expand('%:p:h')
  endif
  let tags = substitute(b:gutentags_files['gtags_cscope'], 'GTAGS', '', 'g')
  if isdirectory(tags)
    return tags
  endif
  return expand('%:p:h')
endfunc

augroup tagdir
  autocmd!
  autocmd BufWinEnter * let g:tagfiledir = s:get_gtags_file_path()
augroup end

nnoremap <leader>fa :<C-U><C-R>=printf("DeniteCursorWord -path='%s' -no-empty -buffer-name=gtags_c gtags_context", g:tagfiledir)<CR><CR>
nnoremap <leader>fd :<C-U><C-R>=printf("DeniteCursorWord -path='%s' -no-empty -buffer-name=gtags_d gtags_def", g:tagfiledir)<CR><CR>
nnoremap <leader>fr :<C-U><C-R>=printf("DeniteCursorWord -path='%s' -no-empty -buffer-name=gtags_r gtags_ref", g:tagfiledir)<CR><CR>
nnoremap <leader>fg :<C-U><C-R>=printf("DeniteCursorWord -path='%s' -no-empty -buffer-name=gtags_g gtags_grep", g:tagfiledir)<CR><CR>
nnoremap <leader>ft :<C-U><C-R>=printf("Denite -path='%s' -no-empty -start-filter -buffer-name=gtags_t gtags_completion", g:tagfiledir)<CR><CR>
nnoremap <leader>ff :<C-U><C-R>=printf("Denite -path='%s' -no-empty -start-filter -buffer-name=gtags_f gtags_file", g:tagfiledir)<CR><CR>
nnoremap <leader>fF :<C-U><C-R>=printf("Denite -path='%s' -no-empty -start-filter -buffer-name=gtags_f gtags_files", g:tagfiledir)<CR><CR>
nnoremap <leader>fp :<C-U><C-R>=printf("Denite -path='%s' -no-empty -start-filter -buffer-name=gtags_p gtags_path", g:tagfiledir)<CR><CR>

```

The probelm is that denite-gtags only can find definition, other key bidings are malfunction. 
But it can work when `GTAGSROOT` and `GTAGSDBPATH` are set correctly.
```os.getcwd()``` is the only way I can find to get current working directory, any better suggestion?

By the way, my os environment is ```Win10``, not sure if it effects how gtags work.

**Comment by ozelentok** [comment]
I have added two buffer variables for setting GTAGSROOT and GTAGSDBPATH
```vim
let b:denite_gtags_root='/path/to/project'
let b:denite_gtags_db_path='/path/to/gtags-db'
```
Please try it out and let me know if it's sufficient or not for what you need

**Comment by dean-ho** [comment]
It works perfectly, thank you.

**Pull request closed without merging**
